export const EMOJI_TAGS = {
  "🇹🇭": "Thai",
  "🇮🇹": "Italian",
  "🇲🇽": "Mexican",
  "🇺🇸": "American",
  "🇯🇵": "Japanese",
  "🇨🇳": "Chinese",
  "🇰🇷": "Korean",
  "🇮🇳": "Indian",
  "🇫🇷": "French",
  "🇬🇷": "Greek",
  "🇻🇳": "Vietnamese",
  "🇵🇭": "Filipino",
  "🌶️": "Spicy",
  "🌶️🌶️": "Very Spicy",
  "🌶️🌶️🌶️": "Extremely Spicy",
  "🧊": "Mild/No Spice, Frozen/Ice Cream",
  "❄️": "Cold Dish",
  "🔥": "Hot Dish",
  "🍳": "Fried",
  "🥘": "Stir-fried",
  "🍲": "Soup/Stew",
  "🥗": "Raw/Salad",
  "🧁": "Baked",
  "🍖": "Grilled/BBQ",
  "🫕": "Hot Pot",
  "🥟": "Steamed",
  "🌱": "Vegetarian",
  "🥬": "Vegan",
  "🥩": "Meat-heavy",
  "🐟": "Seafood",
  "🦐": "Shellfish",
  "🥛": "Dairy-free",
  "🌾": "Gluten-free",
  "🥜": "Contains Nuts",
  "🍯": "Sugar-free",
  "☀️": "Breakfast",
  "🌅": "Brunch",
  "🌞": "Lunch",
  "🌆": "Dinner",
  "🌙": "Late Night",
  "🍰": "Dessert",
  "🥤": "Beverage",
  "🍿": "Snack",
  "👶": "Beginner",
  "👨‍🍳": "Intermediate",
  "👨‍🍳👨‍🍳": "Advanced",
  "⭐": "Chef-level",
  "⚡": "Quick (< 15 min)",
  "⏱️": "Medium (15-45 min)",
  "⏰": "Long (> 45 min)",
  "🐌": "Slow-cooked",
  "🎉": "Party/Entertaining",
  "👨‍👩‍👧‍👦": "Family-friendly",
  "💑": "Date Night",
  "🏥": "Healthy",
  "🍔": "Comfort Food",
  "🎂": "Birthday",
  "🎄": "Holiday",
  "💰": "Budget-friendly",
  "💎": "Expensive/Luxury",
} as const;
