import {
    AppTabKey,
    baseBorderWidths,
    baseComponentSizes,
    baseComponentTokens,
    baseFontFamilies,
    baseIconSizes,
    baseLayout,
    baseLetterSpacing,
    baseLineHeights,
    baseOpacity,
    baseSpacing,
    baseRadii,
    baseTypography,
    FULL_WIDTH,
    ThemeDefinition
} from "./types";

const colors = {
  background: "#FAF8F5",
  surface: "#F5F3F0",
  overlay: "#F0EDE8",
  surfaceVariant: "#e8e2db",
  surfaceSubdued: "#e2dbd2",
  surfaceMuted: "#dcd3c9",
  primary: "#5D4037",
  onPrimary: "#FAF8F5",
  muted: "#d1c7bd",
  textPrimary: "#3D2817",
  textSecondary: "#5A4A3A",
  textMuted: "#8B7D6A",
  border: "#D4C5B5",
  accent: "#5D4037",
  accentOnPrimary: "#FAF8F5",
  success: "#2D8659",
  danger: "#B85C38",
  info: "#4A7C59",
  logoFill: "#3D2817",
  logoPrimaryColor: "#5D4037", // Deep brown - distinct from surface, matches primary
  logoSecondaryColor: "#2D8659", // Lush green - complements brown, distinct from border
  logoTertiaryColor: "#B85C38", // Rust orange - complements brown and green, adds warmth
  imageBackgroundColor: "#F5F3F0",
} as const;

export const classicTheme: ThemeDefinition = {
  label: "Classic",
  description: "Warm light backgrounds with deep browns and lush greens for natural elegance.",
  tokens: {
    colors,
    spacing: baseSpacing,
    padding: {
      screen: 12,
      section: 16,
      card: 10,
      compact: 6,
    },
    radii: {
      sm: 8,
      md: 16,
      lg: 32,
      round: baseRadii.round,
    },
    typography: baseTypography,
    fontFamilies: {
      display: "Sprat-Regular",
      regular: "Sprat-Regular",
      light: "Sprat-Light",
      lightItalic: "Sprat-Light",
      medium: "Sprat-Medium",
      semiBold: "Sprat-Medium",
      bold: "Sprat-Bold",
    },
    layout: baseLayout,
    shadows: {
      card: {
        shadowColor: "#3D2817",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
      },
      floating: {
        shadowColor: "#5D4037",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 6,
      },
    },
    borderWidths: baseBorderWidths,
    lineHeights: baseLineHeights,
    letterSpacing: baseLetterSpacing,
    opacity: baseOpacity,
    iconSizes: baseIconSizes,
    widths: { full: FULL_WIDTH },
    componentSizes: baseComponentSizes,
    components: {
      ...baseComponentTokens,
      tabBar: {
        containerBackground: colors.background,
        slotBackground: colors.background,
        list: {
          paddingHorizontal: baseSpacing.sm,
          paddingVertical: baseSpacing.sm,
          marginHorizontal: baseSpacing.md,
          marginBottom: baseSpacing.lg,
          borderRadius: 36,
          backgroundColor: colors.surface,
          borderWidth: baseBorderWidths.regular,
          borderColor: colors.border,
          shadow: "card",
        },
        trigger: {
          paddingHorizontal: baseSpacing.md,
          paddingVertical: baseSpacing.xs,
          borderRadius: 36,
          minHeight: baseSpacing.xl,
          shape: "pill",
          inactiveBackgroundColor: "transparent",
          activeBackgroundColor: colors.accent,
        },
        label: {
          show: true,
          color: colors.textSecondary,
          activeColor: colors.accentOnPrimary,
          uppercase: false,
          letterSpacing: baseLetterSpacing.normal,
          marginLeftWithIcon: baseSpacing.xs,
        },
          icon: {
            show: false,
            family: "Feather",
            size: baseIconSizes.md,
            inactiveColor: colors.textSecondary,
            activeColor: colors.accentOnPrimary,
            names: {
              home: "home",
              kitchen: "shopping-cart",
              lists: "list",
              creator: "edit-3",
              vendor: "briefcase",
            } satisfies Record<AppTabKey, string>,
          },
        },
      },
    },
  assets: {
    logo: require("@/assets/images/haricot-logo.svg"),
  },
};
