import {
  FULL_WIDTH,
  ThemeDefinition,
  baseBorderWidths,
  baseComponentSizes,
  baseComponentTokens,
  baseFontFamilies,
  baseRadii,
  baseIconSizes,
  baseLayout,
  baseLetterSpacing,
  baseLineHeights,
  baseOpacity,
  baseSpacing,
  baseTypography,
  type AppTabKey,
} from "./types";

const colors = {
  background: "#8CA1C6",
  surface: "#987AA5",
  overlay: "#B8C7DD",
  surfaceVariant: "#ac98b7",
  surfaceSubdued: "#a289b0",
  surfaceMuted: "#8d7299",
  primary: "#CC480F",
  onPrimary: "#FFF3D6",
  muted: "#a9b7d1",
  textPrimary: "#2F2619",
  textSecondary: "#4A3C2A",
  textMuted: "#7A6B52",
  border: "#C78C2C",
  accent: "#CC480F",
  accentOnPrimary: "#FFF3D6",
  success: "#9A9D27",
  danger: "#CC480F",
  info: "#8CA1C6",
  logoFill: "#2F2619",
  logoPrimaryColor: "#CC480F", // Bright orange - distinct from surface, matches accent
  logoSecondaryColor: "#C78C2C", // Golden yellow - complements orange, distinct from border
  imageBackgroundColor: "#987AA5",
} as const;

const radii = {
  sm: 6,
  md: 12,
  lg: 18,
  round: baseRadii.round,
} as const;

export const springfieldTheme: ThemeDefinition = {
  label: "Springfield",
  description: "Playful kitchen pastels with cartoon cabinetry accents inspired by Evergreen Terrace.",
  tokens: {
    colors,
    spacing: baseSpacing,
    padding: {
      screen: 14,
      section: 18,
      card: 12,
      compact: 8,
    },
    radii,
    typography: baseTypography,
    fontFamilies: {
      ...baseFontFamilies,
      display: "OpenDyslexic-Bold",
      semiBold: "W95FA",
      bold: "W95FA",
    },
    layout: baseLayout,
    shadows: {
      card: {
        shadowColor: "#CC480F",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 5,
      },
      floating: {
        shadowColor: "#987AA5",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 8,
      },
    },
    borderWidths: baseBorderWidths,
    lineHeights: baseLineHeights,
    letterSpacing: baseLetterSpacing,
    opacity: baseOpacity,
    iconSizes: baseIconSizes,
    widths: { full: FULL_WIDTH },
    componentSizes: baseComponentSizes,
    components: {
      ...baseComponentTokens,
      tabBar: {
        containerBackground: colors.background,
        slotBackground: colors.background,
        list: {
          paddingHorizontal: baseSpacing.sm,
          paddingVertical: baseSpacing.xs,
          marginHorizontal: baseSpacing.lg,
          marginBottom: baseSpacing.lg,
          borderRadius: radii.lg,
          backgroundColor: colors.surface,
          borderWidth: baseBorderWidths.thin,
          borderColor: colors.border,
          shadow: "card",
        },
        trigger: {
          paddingHorizontal: baseSpacing.md,
          paddingVertical: baseSpacing.sm,
          borderRadius: radii.lg,
          minHeight: baseSpacing.xl,
          shape: "pill",
          inactiveBackgroundColor: colors.overlay,
          activeBackgroundColor: colors.accent,
        },
        label: {
          show: false,
          color: colors.textSecondary,
          activeColor: colors.accentOnPrimary,
          uppercase: true,
          letterSpacing: baseLetterSpacing.normal,
          marginLeftWithIcon: baseSpacing.xs,
        },
        icon: {
          show: true,
          family: "Feather",
          size: baseIconSizes.md,
          inactiveColor: colors.textSecondary,
          activeColor: colors.accentOnPrimary,
          names: {
            home: "home",
            kitchen: "shopping-cart",
            lists: "list",
            creator: "edit-3",
            vendor: "briefcase",
          } satisfies Record<AppTabKey, string>,
        },
      },
    },
  },
  assets: {
    logo: require("@/assets/images/springfield-logo.svg"),
  },
};
