import { Platform, StyleSheet } from "react-native";
import type { ThemeTokens } from "./tokens";

const createHomeStyles = (tokens: ThemeTokens) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: tokens.colors.background,
      minHeight: tokens.spacing.none,
    },
    header: {
      backgroundColor: tokens.colors.surface,
      paddingTop: tokens.layout.headerTopPadding,
      paddingHorizontal: tokens.spacing.lg,
      paddingBottom: tokens.spacing.sm,
      borderBottomWidth: tokens.borderWidths.thin,
      borderBottomColor: tokens.colors.border,
    },
    headerTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },
    title: {
      fontSize: tokens.typography.title,
      fontFamily: tokens.fontFamilies.display,
      textTransform: "uppercase",
      marginBottom: tokens.spacing.xs,
      color: tokens.colors.textPrimary,
    },
    email: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
    },
    logoutButton: {
      paddingHorizontal: tokens.spacing.lg,
      paddingVertical: tokens.spacing.sm,
      borderRadius: tokens.radii.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
    },
    logoutText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textPrimary,
    },
    profileButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: tokens.colors.overlay,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
    },
    tasksContainer: {
      flex: 1,
      minHeight: tokens.spacing.none,
    },
    scrollContent: {
      paddingHorizontal: tokens.spacing.none,
      paddingTop: tokens.spacing.lg,
      paddingBottom: tokens.layout.fabOffset + tokens.spacing.lg,
    },
    userTypeBanner: {
      marginHorizontal: tokens.spacing.lg,
      marginBottom: tokens.spacing.md,
      padding: tokens.spacing.md,
      borderRadius: tokens.radii.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
    },
    userTypeLabel: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    searchSection: {
      marginHorizontal: tokens.spacing.lg,
      marginBottom: tokens.spacing.lg,
      gap: tokens.spacing.xs,
    },
    worldEntry: {
      marginHorizontal: tokens.spacing.lg,
      marginBottom: tokens.spacing.lg,
    },
    worldButton: {
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.md,
      padding: tokens.spacing.lg,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
    },
    worldButtonTitle: {
      fontSize: tokens.typography.heading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    worldButtonSubtitle: {
      marginTop: tokens.spacing.xs,
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.body * tokens.lineHeights.normal,
    },
    ingestionSection: {
      marginHorizontal: tokens.spacing.lg,
      marginBottom: tokens.spacing.xl,
      padding: tokens.spacing.lg,
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.lg,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      gap: tokens.spacing.sm,
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
    },
    ingestionEyebrow: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    ingestionHeadline: {
      fontSize: tokens.typography.heading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
      lineHeight: tokens.typography.heading * tokens.lineHeights.relaxed,
    },
    ingestionBody: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.body * tokens.lineHeights.relaxed,
    },
    ingestionLabel: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
      marginTop: tokens.spacing.sm,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    ingestionCaption: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textMuted,
      lineHeight: tokens.typography.small * tokens.lineHeights.normal,
    },
    sourceTypeRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: tokens.spacing.xs,
    },
    sourcePill: {
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.xs,
      borderRadius: tokens.radii.round,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.overlay,
    },
    sourcePillActive: {
      backgroundColor: tokens.colors.accent,
      borderColor: tokens.colors.accent,
    },
    sourcePillText: {
      color: tokens.colors.textPrimary,
      fontFamily: tokens.fontFamilies.medium,
      fontSize: tokens.typography.small,
      textTransform: "capitalize",
    },
    sourcePillTextActive: {
      color: tokens.colors.accentOnPrimary,
      fontFamily: tokens.fontFamilies.semiBold,
      fontSize: tokens.typography.small,
      textTransform: "capitalize",
    },
    ingestionInput: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      backgroundColor: tokens.colors.surface,
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.xs,
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textPrimary,
    },
    ingestionTextArea: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      backgroundColor: tokens.colors.surface,
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.sm,
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textPrimary,
      minHeight: 120,
    },
    ingestButton: {
      marginTop: tokens.spacing.sm,
      alignSelf: "flex-start",
      backgroundColor: tokens.colors.accent,
      borderRadius: tokens.radii.sm,
      paddingHorizontal: tokens.spacing.lg,
      paddingVertical: tokens.spacing.sm,
      shadowColor: tokens.shadows.floating.shadowColor,
      shadowOffset: tokens.shadows.floating.shadowOffset,
      shadowOpacity: tokens.shadows.floating.shadowOpacity,
      shadowRadius: tokens.shadows.floating.shadowRadius,
      elevation: tokens.shadows.floating.elevation,
    },
    ingestButtonDisabled: {
      opacity: tokens.opacity.disabled,
    },
    ingestButtonText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.accentOnPrimary,
      letterSpacing: tokens.letterSpacing.tight,
      textTransform: "uppercase",
    },
    ingestErrorText: {
      color: tokens.colors.danger,
      fontFamily: tokens.fontFamilies.medium,
      fontSize: tokens.typography.small,
    },
    ingestResultCard: {
      marginTop: tokens.spacing.md,
      padding: tokens.spacing.md,
      borderRadius: tokens.radii.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.overlay,
      gap: tokens.spacing.xs,
    },
    ingestLinkButton: {
      marginTop: tokens.spacing.xs,
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.sm,
      borderRadius: tokens.radii.sm,
      backgroundColor: tokens.colors.surface,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.accent,
    },
    ingestLinkButtonText: {
      color: tokens.colors.accent,
      fontFamily: tokens.fontFamilies.semiBold,
      fontSize: tokens.typography.small,
    },
    ingestionDetailsBox: {
      marginTop: tokens.spacing.sm,
      padding: tokens.spacing.sm,
      borderRadius: tokens.radii.sm,
      backgroundColor: tokens.colors.surface,
      borderWidth: tokens.borderWidths.hairline,
      borderColor: tokens.colors.border,
      gap: tokens.spacing.xs,
    },
    searchLabel: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    searchInput: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      backgroundColor: tokens.colors.surface,
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.xs,
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textPrimary,
    },
    searchResultsContainer: {
      marginTop: tokens.spacing.xs,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.md,
      backgroundColor: tokens.colors.surface,
      overflow: "hidden",
    },
    searchStatusText: {
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.sm,
      fontFamily: tokens.fontFamilies.regular,
      fontSize: tokens.typography.small,
      color: tokens.colors.textSecondary,
    },
    searchResultItem: {
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.sm,
      borderBottomWidth: tokens.borderWidths.thin,
      borderBottomColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
    },
    searchResultTitle: {
      fontFamily: tokens.fontFamilies.semiBold,
      fontSize: tokens.typography.body,
      color: tokens.colors.textPrimary,
    },
    searchResultDescription: {
      marginTop: tokens.spacing.xs,
      fontFamily: tokens.fontFamilies.regular,
      fontSize: tokens.typography.small,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.small * tokens.lineHeights.normal,
    },
    searchViewAllButton: {
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.sm,
      backgroundColor: tokens.colors.accent,
      borderTopWidth: tokens.borderWidths.thin,
      borderTopColor: tokens.colors.border,
      alignItems: "center",
      justifyContent: "center",
    },
    searchViewAllText: {
      fontFamily: tokens.fontFamilies.semiBold,
      fontSize: tokens.typography.small,
      color: tokens.colors.accentOnPrimary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    section: {
      marginBottom: tokens.spacing.xxl,
    },
    seedButtonsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: tokens.spacing.sm,
      marginHorizontal: tokens.spacing.lg,
      marginBottom: tokens.spacing.md,
    },
    seedButton: {
      alignSelf: "flex-start",
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.accent,
      paddingHorizontal: tokens.spacing.lg,
      paddingVertical: tokens.spacing.sm,
    },
    seedButtonDisabled: {
      opacity: tokens.opacity.disabled,
    },
    seedButtonText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.accent,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    sectionTitle: {
      fontSize: tokens.typography.heading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
      marginBottom: tokens.spacing.sm,
    },
    onboardingCard: {
      backgroundColor: tokens.colors.overlay,
      borderRadius: tokens.radii.md,
      padding: tokens.spacing.lg,
      marginBottom: tokens.spacing.lg,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      gap: tokens.spacing.sm,
    },
    onboardingCardTitle: {
      fontSize: tokens.typography.subheading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    onboardingCardDescription: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.small * tokens.lineHeights.normal,
    },
    onboardingButton: {
      alignSelf: "flex-start",
      backgroundColor: tokens.colors.accent,
      borderRadius: tokens.radii.sm,
      paddingHorizontal: tokens.spacing.lg,
      paddingVertical: tokens.spacing.sm,
    },
    onboardingButtonDisabled: {
      opacity: tokens.opacity.disabled,
    },
    onboardingButtonText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.accentOnPrimary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    sectionEmptyText: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textMuted,
      marginTop: tokens.spacing.sm,
      lineHeight: tokens.typography.body * tokens.lineHeights.normal,
    },
    taskCard: {
      backgroundColor: tokens.colors.surface,
      padding: tokens.spacing.lg,
      borderRadius: tokens.radii.md,
      marginBottom: tokens.spacing.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
    },
    taskTitle: {
      fontSize: tokens.typography.subheading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    completedBadge: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.success,
      marginTop: tokens.spacing.sm,
    },
    fab: {
      position: "absolute",
      right: tokens.layout.fabOffset,
      bottom: tokens.layout.fabOffset,
      width: tokens.layout.fabSize,
      height: tokens.layout.fabSize,
      borderRadius: tokens.layout.fabSize / 2,
      backgroundColor: tokens.colors.accent,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: tokens.shadows.floating.shadowColor,
      shadowOffset: tokens.shadows.floating.shadowOffset,
      shadowOpacity: tokens.shadows.floating.shadowOpacity,
      shadowRadius: tokens.shadows.floating.shadowRadius,
      elevation: tokens.shadows.floating.elevation,
      ...(Platform.OS === "web" && { zIndex: 1000 }),
    },
    fabText: {
      fontSize: tokens.typography.title,
      color: tokens.colors.accentOnPrimary,
      fontFamily: tokens.fontFamilies.semiBold,
    },
  });

export default createHomeStyles;
