import { StyleSheet } from "react-native";
import type { ThemeTokens } from "./tokens";

const createKitchenStyles = (tokens: ThemeTokens) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: tokens.colors.background,
      minHeight: tokens.spacing.none,
    },
    header: {
      backgroundColor: tokens.colors.surface,
      paddingTop: tokens.layout.headerTopPadding,
      paddingHorizontal: tokens.spacing.lg,
      paddingBottom: tokens.spacing.sm,
      borderBottomWidth: tokens.borderWidths.thin,
      borderBottomColor: tokens.colors.border,
    },

    headerTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },
    title: {
      fontSize: tokens.typography.title,
      fontFamily: tokens.fontFamilies.display,
      textTransform: "uppercase",
      marginBottom: tokens.spacing.xs,
      color: tokens.colors.textPrimary,
    },
    email: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
    },
    logoutButton: {
      paddingHorizontal: tokens.spacing.lg,
      paddingVertical: tokens.spacing.sm,
      borderRadius: tokens.radii.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
    },
    logoutText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textPrimary,
    },
    profileButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: tokens.colors.overlay,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
    },
    content: {
      flex: 1,
      minHeight: tokens.spacing.none,
    },
    scrollContent: {
      paddingHorizontal: tokens.spacing.lg,
      paddingTop: tokens.spacing.lg,
      paddingBottom: tokens.spacing.xxl,
    },
    sectionDescription: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.body * tokens.lineHeights.normal,
      marginBottom: tokens.spacing.lg,
    },
    controlsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: tokens.spacing.sm,
      marginBottom: tokens.spacing.md,
    },
    controlsLeft: {
      flex: 1,
      minWidth: 0,
    },
    controlsRight: {
      flexShrink: 0,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
    },
    sortControl: {
      position: "relative",
      zIndex: 2,
    },
    sortTrigger: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.lg,
      backgroundColor: tokens.colors.surface,
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.lg,
      gap: tokens.spacing.xxs,
    },
    sortTriggerLabel: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.light,
      textTransform: "uppercase",
      color: tokens.colors.textSecondary,
      letterSpacing: tokens.letterSpacing.tight,
    },
    sortTriggerValue: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    sortMenu: {
      position: "absolute",
      top: "100%",
      left: 0,
      right: 0,
      marginTop: tokens.spacing.xs,
      borderRadius: tokens.radii.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
      overflow: "hidden",
      zIndex: 3,
    },
    sortMenuItem: {
      paddingVertical: tokens.spacing.xxs,
      paddingHorizontal: tokens.spacing.xxs,
    },
    sortMenuItemActive: {
      backgroundColor: tokens.colors.overlay,
    },
    sortMenuLabel: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textPrimary,
    },
    sortMenuLabelActive: {
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.accent,
    },
    viewToggle: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.lg,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      paddingVertical: tokens.spacing.xxs,
      paddingHorizontal: tokens.spacing.xxs,
      gap: tokens.spacing.xxs,
      flexShrink: 0,
    },
    viewToggleButton: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: tokens.spacing.xs,
      paddingHorizontal: tokens.spacing.md,
      borderRadius: tokens.radii.md,
      minWidth: 60,
    },
    viewToggleButtonActive: {
      backgroundColor: tokens.colors.accent,
    },
    viewToggleLabel: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    viewToggleLabelActive: {
      color: tokens.colors.accentOnPrimary,
      fontFamily: tokens.fontFamilies.semiBold,
    },
    filterRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: tokens.spacing.xs,
      marginBottom: tokens.spacing.sm,
    },
    filterPill: {
      paddingVertical: tokens.spacing.xxs,
      paddingHorizontal: tokens.spacing.xxs,
      borderRadius: tokens.radii.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
    },
    filterPillActive: {
      backgroundColor: tokens.colors.accent,
      borderColor: tokens.colors.accent,
    },
    filterPillLabel: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textSecondary,
    },
    filterPillLabelActive: {
      color: tokens.colors.accentOnPrimary,
    },
    listContainer: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.md,
      backgroundColor: tokens.colors.surface,
      overflow: "hidden",
    },
    listHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.sm,
      backgroundColor: tokens.colors.overlay,
      borderBottomWidth: tokens.borderWidths.thin,
      borderBottomColor: tokens.colors.border,
      gap: tokens.spacing.md,
    },
    listHeaderCell: {
      flex: 1,
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    listHeaderCellName: {
      flex: 2,
    },
    listRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.md,
      gap: tokens.spacing.md,
      borderBottomWidth: tokens.borderWidths.thin,
      borderBottomColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
    },
    listCell: {
      flex: 1,
    },
    listCellName: {
      flex: 2,
      gap: tokens.spacing.xxs,
    },
    listItemName: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    listItemMeta: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    listCellQty: {
      alignItems: "flex-start",
    },
    listCellDate: {
      alignItems: "flex-end",
      gap: tokens.spacing.xxs,
    },
    listItemDate: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textPrimary,
    },
    listItemQuantity: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textPrimary,
    },
    grid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    gridItem: {
      width: "48%",
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      overflow: "hidden",
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
      marginBottom: tokens.spacing.md,
    },
    gridMetaBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.xs,
      backgroundColor: tokens.colors.overlay,
      borderBottomWidth: tokens.borderWidths.thin,
      borderBottomColor: tokens.colors.border,
      gap: tokens.spacing.md,
    },
    gridMetaBarLabel: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    gridQuantityPill: {
      paddingHorizontal: tokens.spacing.sm,
      paddingVertical: tokens.spacing.xxs,
      borderRadius: tokens.radii.lg,
      backgroundColor: tokens.colors.surface,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
    },
    gridQuantityPillLabel: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textPrimary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    gridImage: {
      width: tokens.widths.full,
      height: tokens.spacing.xl * 5,
      backgroundColor: tokens.colors.overlay,
    },
    gridContent: {
      padding: tokens.spacing.md,
      gap: tokens.spacing.xs,
    },
    gridName: {
      fontSize: tokens.typography.subheading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    gridVariety: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
    },
    gridMetaRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    gridMetaLabel: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: 'tokens.colors.textSecondary',
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
      borderBottomColor: tokens.colors.border,
    },
    gridMetaValue: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    emptyStateCard: {
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      padding: tokens.spacing.lg,
      alignItems: "flex-start",
    },
    emptyStateTitle: {
      fontSize: tokens.typography.subheading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
      marginBottom: tokens.spacing.xs,
    },
    emptyStateText: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textMuted,
      lineHeight: tokens.typography.body * tokens.lineHeights.normal,
    },
  });

export default createKitchenStyles;
