import { StyleSheet } from "react-native";
import type { ThemeTokens } from "./tokens";

const createListsStyles = (tokens: ThemeTokens) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: tokens.colors.background,
      minHeight: tokens.spacing.none,
    },
    content: {
      flex: 1,
      minHeight: tokens.spacing.none,
    },
    scrollContent: {
      paddingHorizontal: tokens.spacing.lg,
      paddingTop: tokens.spacing.lg,
      paddingBottom: tokens.spacing.xxl,
      gap: tokens.spacing.lg,
    },
    searchSection: {
      gap: tokens.spacing.xxs,
    },
    searchLabel: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    searchInput: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.lg,
      backgroundColor: tokens.colors.surface,
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.sm,
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textPrimary,
    },
    controlsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: tokens.spacing.sm,
    },
    controlsRight: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: tokens.spacing.xs,
    },
    sortControl: {
      position: "relative",
      zIndex: 2,
      flex: 1,
      minWidth: 0,
    },
    sortTrigger: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.lg,
      backgroundColor: tokens.colors.surface,
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.lg,
      gap: tokens.spacing.xxs,
    },
    sortTriggerLabel: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.light,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    sortTriggerValue: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    sortMenu: {
      position: "absolute",
      top: "100%",
      left: 0,
      right: 0,
      marginTop: tokens.spacing.xs,
      borderRadius: tokens.radii.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
      overflow: "hidden",
      zIndex: 3,
    },
    sortMenuItem: {
      paddingVertical: tokens.spacing.xxs,
      paddingHorizontal: tokens.spacing.md,
    },
    sortMenuItemActive: {
      backgroundColor: tokens.colors.overlay,
    },
    sortMenuLabel: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textPrimary,
    },
    sortMenuLabelActive: {
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.accent,
    },
    viewToggle: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.lg,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      paddingVertical: tokens.spacing.xxs,
      paddingHorizontal: tokens.spacing.xxs,
      gap: tokens.spacing.xxs,
    },
    viewToggleButton: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: tokens.spacing.xs,
      paddingHorizontal: tokens.spacing.md,
      borderRadius: tokens.radii.md,
      minWidth: tokens.spacing.xxl,
    },
    viewToggleButtonActive: {
      backgroundColor: tokens.colors.accent,
    },
    viewToggleLabel: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    viewToggleLabelActive: {
      color: tokens.colors.accentOnPrimary,
      fontFamily: tokens.fontFamilies.semiBold,
    },
    filterRowContent: {
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.spacing.xs,
      paddingRight: tokens.spacing.sm,
      paddingLeft: 0,
    },
    filterChip: {
      paddingVertical: tokens.spacing.xxs,
      paddingHorizontal: tokens.spacing.sm,
      borderRadius: tokens.radii.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
    },
    filterChipActive: {
      backgroundColor: tokens.colors.accent,
      borderColor: tokens.colors.accent,
    },
    filterChipLabel: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textSecondary,
    },
    filterChipLabelActive: {
      color: tokens.colors.accentOnPrimary,
    },
    listCollection: {
      gap: tokens.spacing.sm,
    },
    listCard: {
      borderRadius: tokens.radii.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
      paddingHorizontal: tokens.spacing.lg,
      paddingVertical: tokens.spacing.md,
      gap: tokens.spacing.xs,
    },
    listCardPressed: {
      backgroundColor: tokens.colors.overlay,
    },
    listCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.spacing.xs,
    },
    listCardEmoji: {
      fontSize: tokens.typography.heading,
    },
    listCardTitle: {
      flex: 1,
      fontSize: tokens.typography.subheading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    listCardSummary: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.small * tokens.lineHeights.relaxed,
    },
    detailedSection: {
      gap: tokens.spacing.xs,
    },
    railEmptyMessage: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      paddingHorizontal: tokens.padding.card,
    },
    emptyState: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: tokens.spacing.xxl,
      gap: tokens.spacing.xs,
    },
    emptyStateText: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textMuted,
      textAlign: "center",
      lineHeight: tokens.typography.body * tokens.lineHeights.relaxed,
    },
    emptyStateSubtext: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      textAlign: "center",
      lineHeight: tokens.typography.small * tokens.lineHeights.relaxed,
    },
    noResultsText: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      textAlign: "center",
      marginTop: tokens.spacing.lg,
    },
  });

export default createListsStyles;
