import { StyleSheet } from "react-native";
import type { ThemeTokens } from "./tokens";

const createProfileStyles = (tokens: ThemeTokens) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: tokens.colors.background,
    },
    header: {
      backgroundColor: tokens.colors.surface,
      paddingTop: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.lg,
      paddingBottom: tokens.spacing.lg,
      borderBottomWidth: tokens.borderWidths.thin,
      borderBottomColor: tokens.colors.border,
    },
    headerProfile: {
      backgroundColor: tokens.colors.surface,
      paddingTop: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.lg,
      paddingBottom: tokens.spacing.sm,
      borderBottomWidth: tokens.borderWidths.thin,
      borderBottomColor: tokens.colors.border,
      textTransform: "uppercase",
    },
    headerTop: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    headerLeft: {
      flex: 1,
    },
    title: {
      fontSize: tokens.typography.title,
      fontFamily: tokens.fontFamilies.display,
      textTransform: "uppercase",
      marginBottom: tokens.spacing.xs,
      color: tokens.colors.textPrimary,
    },
    email: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
    },
    logoutButton: {
      paddingHorizontal: tokens.spacing.lg,
      paddingVertical: tokens.spacing.sm,
      borderRadius: tokens.radii.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      backgroundColor: tokens.colors.surface,
    },
    logoutText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.medium,
      color: tokens.colors.textPrimary,
    },
    content: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: tokens.spacing.xxs,
      paddingTop: tokens.spacing.lg,
      paddingBottom: tokens.spacing.xxl,
      gap: tokens.spacing.md,
    },
    householdCard: {
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      padding: tokens.spacing.lg,
      gap: tokens.spacing.sm,
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
    },
    householdOverline: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    householdStatusText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.small * tokens.lineHeights.normal,
    },
    householdDescription: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.small * tokens.lineHeights.normal,
    },
    householdCodeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.spacing.sm,
    },
    codeBadge: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.lg,
      backgroundColor: tokens.colors.overlay,
    },
    codeText: {
      fontSize: tokens.typography.subheading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
      letterSpacing: tokens.letterSpacing.tight,
    },
    copyButton: {
      backgroundColor: tokens.colors.accent,
      borderRadius: tokens.radii.sm,
      paddingHorizontal: tokens.spacing.lg,
      paddingVertical: tokens.spacing.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.accent,
    },
    copyButtonCopied: {
      backgroundColor: tokens.colors.overlay,
      borderColor: tokens.colors.accent,
    },
    copyButtonError: {
      backgroundColor: tokens.colors.danger,
      borderColor: tokens.colors.danger,
    },
    copyButtonText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.accentOnPrimary,
    },
    copyButtonErrorText: {
      color: tokens.colors.surface,
    },
    householdMessage: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      lineHeight: tokens.typography.tiny * tokens.lineHeights.normal,
    },
    householdMessageInfo: {
      color: tokens.colors.info,
    },
    householdMessageSuccess: {
      color: tokens.colors.success,
    },
    householdMessageError: {
      color: tokens.colors.danger,
    },
    memberSection: {
      gap: tokens.spacing.sm,
    },
    memberSectionTitle: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    memberRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: tokens.spacing.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.md,
      backgroundColor: tokens.colors.surface,
    },
    memberInfo: {
      flex: 1,
      gap: tokens.spacing.xs,
    },
    memberName: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    memberEmail: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.tiny * tokens.lineHeights.normal,
    },
    pendingHint: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textMuted,
    },
    allergySection: {
      gap: tokens.spacing.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      padding: tokens.spacing.md,
      backgroundColor: tokens.colors.surface,
    },
    allergyDescription: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.tiny * tokens.lineHeights.normal,
    },
    allergyGroup: {
      gap: tokens.spacing.sm,
    },
    memberSubheading: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    chipList: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: tokens.spacing.xs,
    },
    chip: {
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.spacing.xs,
      backgroundColor: tokens.colors.overlay,
      borderRadius: tokens.radii.lg,
      paddingVertical: tokens.spacing.xs,
      paddingHorizontal: tokens.spacing.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
    },
    chipText: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    chipRemove: {
      paddingHorizontal: tokens.spacing.xs,
    },
    chipRemoveText: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textSecondary,
    },
    inlineInputRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: tokens.spacing.xs,
    },
    inlineInput: {
      flex: 1,
    },
    inlinePrimaryButton: {
      backgroundColor: tokens.colors.accent,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.md,
      alignItems: "center",
      justifyContent: "center",
    },
    inlinePrimaryButtonText: {
      color: tokens.colors.accentOnPrimary,
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
    },
    allergyEmptyText: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textMuted,
    },
    childSection: {
      gap: tokens.spacing.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      padding: tokens.spacing.md,
      backgroundColor: tokens.colors.surface,
    },
    childCard: {
      gap: tokens.spacing.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      padding: tokens.spacing.md,
      backgroundColor: tokens.colors.surface,
    },
    childHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    childName: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    childEditButton: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.xs,
      paddingHorizontal: tokens.spacing.md,
      backgroundColor: tokens.colors.surface,
    },
    childEditButtonText: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    childEditor: {
      gap: tokens.spacing.sm,
    },
    childEditorActions: {
      flexDirection: "row",
      gap: tokens.spacing.sm,
    },
    dangerOutlineButton: {
      flex: 1,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.danger,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      alignItems: "center",
      backgroundColor: tokens.colors.surface,
    },
    dangerOutlineButtonText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.danger,
    },
    newChildForm: {
      gap: tokens.spacing.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      padding: tokens.spacing.md,
      backgroundColor: tokens.colors.surface,
    },
    confirmButton: {
      backgroundColor: tokens.colors.accent,
      borderRadius: tokens.radii.sm,
      paddingHorizontal: tokens.spacing.md,
      paddingVertical: tokens.spacing.sm,
    },
    confirmButtonText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.accentOnPrimary,
    },
    manageButton: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.md,
      backgroundColor: tokens.colors.surface,
      alignItems: "center",
    },
    manageButtonActive: {
      borderColor: tokens.colors.accent,
      backgroundColor: tokens.colors.overlay,
    },
    manageButtonText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    manageSection: {
      gap: tokens.spacing.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      padding: tokens.spacing.md,
      backgroundColor: tokens.colors.surface,
    },
    manageDescription: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.small * tokens.lineHeights.normal,
    },
    manageLabel: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    manageInput: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.md,
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textPrimary,
      backgroundColor: tokens.colors.surface,
    },
    manageHelper: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textMuted,
      lineHeight: tokens.typography.tiny * tokens.lineHeights.normal,
    },
    manageActions: {
      flexDirection: "row",
      gap: tokens.spacing.sm,
    },
    managePrimaryButton: {
      flex: 1,
      backgroundColor: tokens.colors.accent,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      alignItems: "center",
    },
    managePrimaryText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.accentOnPrimary,
    },
    manageSecondaryButton: {
      flex: 1,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.danger,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      alignItems: "center",
      backgroundColor: tokens.colors.surface,
    },
    manageSecondaryText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.danger,
    },
    disabledControl: {
      opacity: tokens.opacity.disabled,
    },
    logoRow: {
      alignItems: "center",
    },
    appearanceCard: {
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      padding: tokens.spacing.lg,
      gap: tokens.spacing.sm,
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
    },
    appearanceTitle: {
      fontSize: tokens.typography.subheading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    appearanceDescription: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.small * tokens.lineHeights.normal,
    },
    accessibilityCard: {
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      padding: tokens.spacing.lg,
      gap: tokens.spacing.md,
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
    },
    accessibilityDescription: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.small * tokens.lineHeights.normal,
    },
    textSizeGroup: {
      gap: tokens.spacing.sm,
    },
    textSizeOption: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      padding: tokens.spacing.md,
      backgroundColor: tokens.colors.surface,
      gap: tokens.spacing.xs,
    },
    textSizeOptionActive: {
      borderColor: tokens.colors.accent,
      backgroundColor: tokens.colors.overlay,
    },
    textSizeOptionTitle: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    textSizeOptionDescription: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.tiny * tokens.lineHeights.normal,
    },
    accessibilityToggle: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.md,
      paddingHorizontal: tokens.spacing.lg,
      backgroundColor: tokens.colors.surface,
      gap: tokens.spacing.xs,
    },
    accessibilityToggleRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: tokens.spacing.xs,
    },
    accessibilityToggleText: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    accessibilityToggleDescription: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.tiny * tokens.lineHeights.normal,
    },
    accessibilityStatus: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textMuted,
    },
    infoCard: {
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      padding: tokens.spacing.lg,
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
      gap: tokens.spacing.sm,
    },
    infoRow: {
      gap: tokens.spacing.xs,
    },
    infoLabel: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: tokens.letterSpacing.tight,
    },
    infoValue: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textPrimary,
      lineHeight: tokens.typography.body * tokens.lineHeights.normal,
    },
    emptyStateText: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textMuted,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: tokens.colors.overlay,
      justifyContent: "center",
      alignItems: "center",
      padding: tokens.spacing.lg,
    },
    modalCard: {
      width: tokens.widths.full,
      maxWidth: tokens.layout.maxFormWidth,
      backgroundColor: tokens.colors.surface,
      borderRadius: tokens.radii.md,
      padding: tokens.spacing.lg,
      gap: tokens.spacing.md,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      shadowColor: tokens.shadows.card.shadowColor,
      shadowOffset: tokens.shadows.card.shadowOffset,
      shadowOpacity: tokens.shadows.card.shadowOpacity,
      shadowRadius: tokens.shadows.card.shadowRadius,
      elevation: tokens.shadows.card.elevation,
    },
    modalTitle: {
      fontSize: tokens.typography.subheading,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    modalDescription: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
      lineHeight: tokens.typography.small * tokens.lineHeights.normal,
    },
    modalMemberList: {
      gap: tokens.spacing.sm,
    },
    modalMemberRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: tokens.spacing.sm,
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.md,
      backgroundColor: tokens.colors.surface,
    },
    modalMemberInfo: {
      flex: 1,
      gap: tokens.spacing.xs,
    },
    modalMemberName: {
      fontSize: tokens.typography.body,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.textPrimary,
    },
    modalMemberEmail: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textSecondary,
    },
    modalMemberHint: {
      fontSize: tokens.typography.tiny,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textMuted,
    },
    modalConfirmButton: {
      backgroundColor: tokens.colors.accent,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      paddingHorizontal: tokens.spacing.md,
    },
    modalConfirmButtonText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.accentOnPrimary,
    },
    modalActions: {
      gap: tokens.spacing.sm,
      flexDirection: "column",
    },
    modalPrimaryButton: {
      backgroundColor: tokens.colors.accent,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      alignItems: "center",
    },
    modalPrimaryButtonText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.semiBold,
      color: tokens.colors.accentOnPrimary,
    },
    modalSecondaryButton: {
      borderWidth: tokens.borderWidths.thin,
      borderColor: tokens.colors.border,
      borderRadius: tokens.radii.sm,
      paddingVertical: tokens.spacing.sm,
      alignItems: "center",
      backgroundColor: tokens.colors.surface,
    },
    modalSecondaryButtonText: {
      fontSize: tokens.typography.small,
      fontFamily: tokens.fontFamilies.regular,
      color: tokens.colors.textPrimary,
    },
  });

export default createProfileStyles;
